##############################################################################
# iviadcgw

apiVersion: v1
kind: Pod

metadata:
  name: iviadcgw
  labels:
    app: iviadcgw

spec:
  serviceAccountName: isva-vc
  automountServiceAccountToken: false

  volumes:
    - name: config-volume
      configMap:
        name: isva-vc-iviadcgw
    - name: ca-cert
      configMap:
        name: isva-vc-iviadc-ca

  containers:
    - name: iviadcgw

      # The fully qualified name of the image.
      image: icr.io/ibmappgateway/ibm-application-gateway:25.06

      # The port on which the container will be listening.
      ports:
        - containerPort: 8443
        
      resources:
        limits:
          memory: "512Mi"
        requests:
          memory: "256Mi"

      volumeMounts:
        - name: config-volume
          mountPath: /var/iag/config
        - name: ca-cert
          mountPath: /etc/ssl/certs/iviadc-ca.pem
          subPath: iviadc-ca.pem
        - name: ca-cert
          mountPath: /etc/ssl/certs/verify_intermediate_pub.crt
          subPath: verify_intermediate_pub.crt
        - name: ca-cert
          mountPath: /etc/ssl/certs/verify_root_pub.crt
          subPath: verify_root_pub.crt

---
# The exported services. Note this is a cluster ip service only.
apiVersion: v1
kind: Service
metadata:
  name: iviadcgw
spec:
  ports:
    - port: 8443
      name: iviadcgw
      protocol: TCP
  selector:
    app: iviadcgw

